#ifndef NAND_STATUS_H
#define NAND_STATUS_H
typedef enum { NAND_OK=0, NAND_ERR_PROFILE=-1, NAND_ERR_ID=-2, NAND_ERR_VOLTAGE=-3, NAND_ERR_DESTRUCTIVE_RANGE=-4, NAND_ERR_PREREQ=-5, NAND_ERR_TIMEOUT=-6, NAND_ERR_ECC=-7, NAND_ERR_HARDWARE_GATED=-8 } nand_status_t;
#endif
