from enum import Enum
class PageState(str, Enum):
    ERASED='ERASED'; PROGRAM_PENDING='PROGRAM_PENDING'; PROGRAMMED_VALID='PROGRAMMED_VALID'; PROGRAMMED_INVALID='PROGRAMMED_INVALID'; READ_DISTURBED='READ_DISTURBED'; PROGRAM_FAILED='PROGRAM_FAILED'; UNCORRECTABLE='UNCORRECTABLE'; RESERVED='RESERVED'; BAD_FACTORY='BAD_FACTORY'; BAD_RUNTIME='BAD_RUNTIME'
