#!/usr/bin/env python3
"""Generate the learner-facing project catalog and project landing pages."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROJECTS = ROOT / "projects"
PROJECT_ROOTS = [
    ("Breadboard", PROJECTS / "breadboard"),
    ("Digital buses", PROJECTS / "buses"),
    ("Storage", PROJECTS / "storage"),
]
GENERATED_NOTICE = (
    "<!-- Generated by tools/generate_project_discovery.py; do not edit by hand. -->"
)


def scalar(text: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:\s*(.+)$", text, flags=re.MULTILINE)
    if not match:
        raise ValueError(f"missing {key}")
    return match.group(1).strip().strip("\"'")


def list_value(text: str, key: str) -> list[str]:
    value = scalar(text, key)
    if value == "[]":
        return []
    if not value.startswith("[") or not value.endswith("]"):
        raise ValueError(f"{key} must be an inline list")
    return [
        item.strip().strip("\"'")
        for item in value[1:-1].split(",")
        if item.strip()
    ]


def humanize(value: str) -> str:
    return value.replace("-", " ").replace("_", " ").title()


def project_records() -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    for category, category_path in PROJECT_ROOTS:
        for project_path in sorted(category_path.glob("[0-9][0-9]-*")):
            contract = (project_path / "project.yaml").read_text(encoding="utf-8")
            project_id = scalar(contract, "projectId")
            if project_id != project_path.name:
                raise ValueError(
                    f"{project_path}: projectId {project_id!r} does not match directory"
                )
            records.append(
                {
                    "category": category,
                    "category_slug": category_path.name,
                    "path": project_path,
                    "id": project_id,
                    "number": project_id[:2],
                    "title": scalar(contract, "title"),
                    "difficulty": humanize(scalar(contract, "difficulty")),
                    "minutes": int(scalar(contract, "estimatedMinutes")),
                    "board": scalar(contract, "primaryBoard"),
                    "voltage": scalar(contract, "supplyVoltage"),
                    "interfaces": list_value(contract, "interfaces"),
                    "prerequisites": list_value(contract, "prerequisites"),
                    "status": scalar(contract, "hardwareValidationStatus"),
                }
            )
    return records


def evidence_label(status: str) -> str:
    if status == "HARDWARE_VALIDATION_REQUIRED":
        return "Hardware evidence required"
    return humanize(status)


def catalog(records: list[dict[str, object]]) -> str:
    lines = [
        GENERATED_NOTICE,
        "# Visual Project Catalog",
        "",
        "Choose a numbered project, inspect its build image, then open the code or",
        "full validation path. The visual layer is an entry point; BOM, safety,",
        "measurement and evidence contracts remain authoritative.",
        "",
        "## Sequence",
        "",
        "Breadboard fundamentals → digital buses → storage integrity → controller work.",
        "",
        "## Quick index",
        "",
    ]
    for record in records:
        lines.append(
            f"{record['number']}. [{record['title']}]"
            f"({record['category_slug']}/{record['id']}/README.md)"
        )
    lines.append("")
    for category, _category_path in PROJECT_ROOTS:
        lines.extend([f"## {category}", ""])
        for record in records:
            if record["category"] != category:
                continue
            project_id = str(record["id"])
            category_slug = str(record["category_slug"])
            interfaces = record["interfaces"]
            interface_label = (
                ", ".join(str(item) for item in interfaces)
                if interfaces
                else "Physical measurement"
            )
            lines.extend(
                [
                    f"### {record['number']} — {record['title']}",
                    "",
                    (
                        f'<img src="../assets/projects/{project_id}/breadboard.svg" '
                        f'width="360" alt="{record["title"]} breadboard connection map">'
                    ),
                    "",
                    (
                        f"**{record['difficulty']} · {record['minutes']} minutes · "
                        f"{record['board']} · {record['voltage']} · {interface_label}**"
                    ),
                    "",
                    (
                        f"[Start project]({category_slug}/{project_id}/README.md) · "
                        f"[Open code]({category_slug}/{project_id}/CODE/) · "
                        f"[Breadboard map](../assets/projects/{project_id}/breadboard.svg) · "
                        f"[Electrical schematic](../assets/projects/{project_id}/schematic.svg)"
                    ),
                    "",
                    f"Evidence status: **{evidence_label(str(record['status']))}**.",
                    "",
                    "---",
                    "",
                ]
            )
    lines.extend(
        [
            "## Advanced project",
            "",
            "### Sovereign Cartridge Proto-0",
            "",
            '<img src="../hardware/platforms/sovereign_cartridge_proto0/'
            'schematics/rendered-schematic.svg" width="720" '
            'alt="Sovereign Cartridge Proto-0 schematic review rendering">',
            "",
            "RP2354A A4 with separate boot and payload NOR, explicit recovery access,",
            "and evidence-gated hardware development.",
            "",
            "[Open platform](../hardware/platforms/sovereign_cartridge_proto0/README.md) · "
            "[Open schematic status](../hardware/platforms/"
            "sovereign_cartridge_proto0/schematics/README.md)",
            "",
            "Evidence status: **Design only; hardware authorization remains disabled**.",
            "",
            "## Engineering paths",
            "",
            "1. [`breadboard/`](breadboard/README.md) — continuity, current, GPIO, switching and ADC.",
            "2. [`buses/`](buses/README.md) — framed UART, register-level I²C and visible SPI.",
            "3. [`storage/`](storage/README.md) — SPI EEPROM and crash-safe SPI NOR.",
            "4. [`ssd_lab/`](ssd_lab/README.md) — raw NAND, FTL, ECC, mapping and controller validation.",
            "",
            "New contributors should start from "
            "[`templates/physical-project/`](../templates/physical-project/).",
            "",
        ]
    )
    return "\n".join(lines)


def landing_page(record: dict[str, object]) -> str:
    project_id = str(record["id"])
    interfaces = record["interfaces"]
    interface_label = (
        ", ".join(str(item) for item in interfaces)
        if interfaces
        else "Physical measurement"
    )
    prerequisites = [
        str(item) for item in record["prerequisites"] if str(item).lower() != "none"
    ]
    prerequisite_label = ", ".join(prerequisites) if prerequisites else "None"
    return "\n".join(
        [
            GENERATED_NOTICE,
            f"# {record['number']} — {record['title']}",
            "",
            (
                f"**{record['difficulty']} · {record['minutes']} minutes · "
                f"{record['board']} · {record['voltage']}**"
            ),
            "",
            (
                "[Start build](BUILD.md) · [Open code](CODE/) · [Wiring table](WIRING.md) · "
                "[Expected result](EXPECTED.md) · "
                "[Validation checklist](validation/checklist.md)"
            ),
            "",
            f"Interface: **{interface_label}**. Prerequisite: **{prerequisite_label}**.",
            "",
            f"Evidence status: **{evidence_label(str(record['status']))}**.",
            "",
            "## Breadboard connection map",
            "",
            f"![{record['title']} breadboard connection map]"
            f"(../../../assets/projects/{project_id}/breadboard.svg)",
            "",
            "Use this image for physical orientation. Confirm every node against the",
            "wiring table, pin map and continuity measurements before applying power.",
            "",
            "## Electrical schematic",
            "",
            f"![{record['title']} electrical schematic]"
            f"(../../../assets/projects/{project_id}/schematic.svg)",
            "",
            "The schematic defines electrical connectivity. It is not evidence that the",
            "physical build has been assembled or measured.",
            "",
            "## Complete project record",
            "",
            "- [Purpose and success condition](PROJECT.md)",
            "- [Why the experiment matters](WHY.md)",
            "- [Parts and sourcing](BUY.md)",
            "- [Power-up safety gate](BEFORE-YOU-POWER.md)",
            "- [Debugging path](DEBUG.md)",
            "- [Measurement procedure](MEASURE.md)",
            "- [Fault-injection exercise](BREAK-IT.md)",
            "- [Evidence folder](evidence/README.md)",
            "- [Next project](NEXT.md)",
            "",
        ]
    )


def expected_outputs() -> dict[Path, str]:
    records = project_records()
    outputs = {PROJECTS / "README.md": catalog(records)}
    for record in records:
        outputs[Path(record["path"]) / "README.md"] = landing_page(record)
    return {path: content.rstrip() + "\n" for path, content in outputs.items()}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed discovery pages differ from generated output",
    )
    arguments = parser.parse_args()

    outputs = expected_outputs()
    stale = [
        path
        for path, expected in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if arguments.check:
        if stale:
            for path in stale:
                print(f"STALE: {path.relative_to(ROOT)}")
            print("Run: python3 tools/generate_project_discovery.py")
            return 1
        print(f"Project discovery pages are current: {len(outputs)} generated files.")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Generated {len(outputs)} project discovery files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
